### ISSUE TITLE
AssertionError in check_squonk_active()

### ISSUE THREAD

**Issue by alanbchristie** [m2ms/fragalysis-frontend#1069]
Found by Boris & Robert this morning.

I sometimes get http code 500 from backend but Robert gets it every time and is blocked. It seems like sometimes backend needs the org uuid and sometimes it doesn't. The log looks like this: -

```
web_dock                        | 2023-06-20T08:19:54+0000 viewer.squonk2_agent.get_squonk2_agent():1019 DEBUG # Created
web_dock                        | 2023-06-20T08:20:01+0000 viewer.views.react():692 INFO # Checking whether Squonk2 is configured...
web_dock                        | 2023-06-20T08:20:01+0000 viewer.views.react():695 INFO # Squonk2 is configured
web_dock                        | 2023-06-20T08:20:01+0000 viewer.discourse.get_user():14 INFO # + discourse.get_user
web_dock                        | 2023-06-20T08:20:02+0000 pydiscourse.client._request():1390 DEBUG # response 503: '<html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body>\r\n<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n<hr><center>nginx/1.19.2</center>\r\n</body>\r\n</html>\r\n'
web_dock                        | 2023-06-20T08:20:02+0000 viewer.discourse.get_user():34 INFO # - discourse.get_user
web_dock                        | 2023-06-20T08:20:02+0000 viewer.squonk_job_request.check_squonk_active():30 INFO # + Squonk2Agent.ping()
web_dock                        | 2023-06-20T08:20:02+0000 viewer.squonk2_agent._get_squonk2_owner_tokens():239 DEBUG # __keycloak_hostname="keycloak.xchem-dev.diamond.ac.uk" __keycloak_realm="xchem" dm-client=data-manager-api-dev as-client=account-server-api-dev org_owner=account-server-api-dev
web_dock                        | 2023-06-20T08:20:03+0000 django.request.log_response():230 ERROR # Internal Server Error: /viewer/react/landing
web_dock                        | Traceback (most recent call last):
web_dock                        |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
web_dock                        |     response = get_response(request)
web_dock                        |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 181, in _get_response
web_dock                        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_dock                        |   File "/code/viewer/views.py", line 721, in react
web_dock                        |     if sq2_rv.success and check_squonk_active(request):
web_dock                        |   File "/code/viewer/squonk_job_request.py", line 32, in check_squonk_active
web_dock                        |     ping_rv = _SQ2A.ping()
web_dock                        |   File "/usr/local/lib/python3.7/dist-packages/wrapt/decorators.py", line 527, in _synchronized_wrapper
web_dock                        |     return wrapped(*args, **kwargs)
web_dock                        |   File "/code/viewer/squonk2_agent.py", line 806, in ping
web_dock                        |     status, msg = self._pre_flight_checks()
web_dock                        |   File "/code/viewer/squonk2_agent.py", line 295, in _pre_flight_checks
web_dock                        |     org_id=self.__CFG_SQUONK2_ORG_UUID)
web_dock                        |   File "/usr/local/lib/python3.7/dist-packages/wrapt/decorators.py", line 527, in _synchronized_wrapper
web_dock                        |     return wrapped(*args, **kwargs)
web_dock                        |   File "/usr/local/lib/python3.7/dist-packages/squonk2/as_api.py", line 515, in get_organisation
web_dock                        |     assert org_id
web_dock                        | AssertionError
```

**Comment by alanbchristie** [comment]
This error is odd because the path _should_ be protected by a prior check that ensures the organisation ID is set, but I will make changes to add trace to identify why this is happening.
