### ISSUE TITLE
job_file_transfer fails

### ISSUE THREAD

**Issue by boriskovar-m2ms** [m2ms/fragalysis-frontend#1187]
After calling job_file_transfer it fails

**Comment by boriskovar-m2ms** [comment]
[backend-lb00000-frag1.0.log](https://github.com/m2ms/fragalysis-frontend/files/13113927/backend-lb00000-frag1.0.log)

**Comment by boriskovar-m2ms** [comment]
[backend-lb18145-1.log](https://github.com/m2ms/fragalysis-frontend/files/13114015/backend-lb18145-1.log)

**Comment by boriskovar-m2ms** [comment]
payload:
```json
{
    "snapshot": 1,
    "access": 1,
    "session_project": 1,
    "target": 1,
    "squonk_project": "project-8f32b412-8329-4469-a39c-8581efa93796",
    "proteins": "Mpro-J0013_A_501_Mpro-J0101+A+410,Mpro-J0030_A_410_Mpro-J0101+A+410,Mpro-J0030_B_403_Mpro-J0101+A+410",
    "compounds": ""
}
````

**Comment by boriskovar-m2ms** [comment]
response:
```
AttributeError at /api/job_file_transfer/
'JobFileTransfer' object has no attribute 'sub_path'

Request Method: POST
Request URL: http://127.0.0.1:8080/api/job_file_transfer/
Django Version: 3.2.20
Python Executable: /usr/local/bin/python
Python Version: 3.11.5
Python Path: ['/code', '/code', '/usr/local/bin', '/usr/local/lib/python311.zip', '/usr/local/lib/python3.11', '/usr/local/lib/python3.11/lib-dynload', '/usr/local/lib/python3.11/site-packages']
Server time: Wed, 25 Oct 2023 06:43:22 +0000
Installed Applications:
['django.contrib.auth',
 'django.contrib.admin',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'scoring',
 'network',
 'viewer',
 'api',
 'hypothesis',
 'hotspots',
 'media_serve',
 'xchem_db',
 'bootstrap3',
 'guardian',
 'graphene_django',
 'django_filters',
 'mozilla_django_oidc',
 'django_extensions',
 'rest_framework',
 'rest_framework.authtoken',
 'rest_framework_swagger',
 'webpack_loader',
 'django_cleanup',
 'simple_history']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'mozilla_django_oidc.middleware.SessionRefresh']


Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/viewer/views.py", line 1688, in create
    if job_transfer.sub_path:

Exception Type: AttributeError at /api/job_file_transfer/
Exception Value: 'JobFileTransfer' object has no attribute 'sub_path'
Request information:
USER: spf57946

GET: No GET data

POST: No POST data

FILES: No FILES data

COOKIES:
csrftoken = 'bBsXfuL4rwCqnjpi2gaBDSKoBNNwWP3PxFVBqaEOSOlwND01VZKJCQJXvBbnHB4m'
sessionid = 'o9xh2wy598e6kfhhbxdv6xmathzmwere'

META:
CONTENT_LENGTH = '250'
CONTENT_TYPE = 'application/json'
CSRF_COOKIE = 'bBsXfuL4rwCqnjpi2gaBDSKoBNNwWP3PxFVBqaEOSOlwND01VZKJCQJXvBbnHB4m'
HTTP_ACCEPT = 'application/json'
HTTP_ACCEPT_ENCODING = 'gzip, deflate, br'
HTTP_ACCEPT_LANGUAGE = 'en-US,en;q=0.9'
HTTP_CONNECTION = 'close'
HTTP_COOKIE = 'csrftoken=bBsXfuL4rwCqnjpi2gaBDSKoBNNwWP3PxFVBqaEOSOlwND01VZKJCQJXvBbnHB4m; sessionid=o9xh2wy598e6kfhhbxdv6xmathzmwere'
HTTP_HOST = '127.0.0.1:8080'
HTTP_ORIGIN = 'http://127.0.0.1:8080'
HTTP_REFERER = 'http://127.0.0.1:8080/viewer/react/projects/1'
HTTP_SEC_CH_UA = '"Chromium";v="118", "Google Chrome";v="118", "Not=A?Brand";v="99"'
HTTP_SEC_CH_UA_MOBILE = '?0'
HTTP_SEC_CH_UA_PLATFORM = '"Windows"'
HTTP_SEC_FETCH_DEST = 'empty'
HTTP_SEC_FETCH_MODE = 'cors'
HTTP_SEC_FETCH_SITE = 'same-origin'
HTTP_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36'
HTTP_X_CSRFTOKEN = '********************'
HTTP_X_FORWARDED_FOR = '172.19.0.1'
HTTP_X_FORWARDED_PROTO = 'http'
HTTP_X_REAL_IP = '172.19.0.1'
HTTP_X_REQUESTED_WITH = 'XMLHttpRequest'
PATH_INFO = '/api/job_file_transfer/'
QUERY_STRING = ''
RAW_URI = '/api/job_file_transfer/'
REMOTE_ADDR = ''
REQUEST_METHOD = 'POST'
SCRIPT_NAME = ''
SERVER_NAME = '127.0.0.1'
SERVER_PORT = '8080'
SERVER_PROTOCOL = 'HTTP/1.0'
SERVER_SOFTWARE = 'gunicorn/21.2.0'
gunicorn.socket = <socket.socket fd=4, family=1, type=1, proto=0, laddr=django_app.sock>
wsgi.errors = <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7fa64d7a7f10>
wsgi.file_wrapper = <class 'gunicorn.http.wsgi.FileWrapper'>
wsgi.input = <gunicorn.http.body.Body object at 0x7fa64c53fdd0>
wsgi.input_terminated = True
wsgi.multiprocess = True
wsgi.multithread = False
wsgi.run_once = False
wsgi.url_scheme = 'http'
wsgi.version = '(1, 0)'

Settings:
Using settings module fragalysis.settings
ABSOLUTE_URL_OVERRIDES = {}
ADMINS = []
ALLOWED_HOSTS = ['*']
ANONYMOUS_USER = 1
APPEND_SLASH = True
AUTHENTICATE_UPLOAD = False
AUTHENTICATION_BACKENDS = "('django.contrib.auth.backends.ModelBackend', 'fragalysis.auth.KeycloakOIDCAuthenticationBackend', 'guardian.backends.ObjectPermissionBackend')"
AUTH_PASSWORD_VALIDATORS = '********************'
AUTH_USER_MODEL = 'auth.User'
BASE_DIR = '/code'
CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_KEY_PREFIX = '********************'
CACHE_MIDDLEWARE_SECONDS = 600
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_URL = 'redis://redis:6379/'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND_ALWAYS_RETRY = True
CELERY_RESULT_EXPIRES = datetime.timedelta(days=15)
CELERY_TASK_ALWAYS_EAGER = True
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
CHEMCENTRAL_DB_NAME = 'UNKOWN'
CSRF_COOKIE_AGE = 31449600
CSRF_COOKIE_DOMAIN = None
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_PATH = '/'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS = []
CSRF_USE_SESSIONS = False
DATABASES = {'default': {'ENGINE': 'django.db.backends.postgresql_psycopg2', 'NAME': 'frag', 'USER': 'fragalysis', 'PASSWORD': '********************', 'HOST': 'database', 'PORT': '5432', 'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True, 'CONN_MAX_AGE': 0, 'OPTIONS': {}, 'TIME_ZONE': None, 'TEST': {'CHARSET': None, 'COLLATION': None, 'MIGRATE': True, 'MIRROR': None, 'NAME': None}}}
DATABASE_ROUTERS = ['xchem_db.routers.AuthRouter']
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000
DATA_UPLOAD_MAX_NUMBER_FILES = 100
DATETIME_FORMAT = 'N j, Y, P'
DATETIME_INPUT_FORMATS = ['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M', '%m/%d/%Y %H:%M:%S', '%m/%d/%Y %H:%M:%S.%f', '%m/%d/%Y %H:%M', '%m/%d/%y %H:%M:%S', '%m/%d/%y %H:%M:%S.%f', '%m/%d/%y %H:%M']
DATE_FORMAT = 'N j, Y'
DATE_INPUT_FORMATS = ['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', '%b %d %Y', '%b %d, %Y', '%d %b %Y', '%d %b, %Y', '%B %d %Y', '%B %d, %Y', '%d %B %Y', '%d %B, %Y']
DEBUG = True
DEBUG_PROPAGATE_EXCEPTIONS = False
DECIMAL_SEPARATOR = '.'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DEFAULT_CHARSET = 'utf-8'
DEFAULT_EXCEPTION_REPORTER = 'django.views.debug.ExceptionReporter'
DEFAULT_EXCEPTION_REPORTER_FILTER = 'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
DEFAULT_FROM_EMAIL = 'webmaster@localhost'
DEFAULT_HASHING_ALGORITHM = 'sha256'
DEFAULT_INDEX_TABLESPACE = ''
DEFAULT_TABLESPACE = ''
DISABLE_LOGGING_FRAMEWORK = False
DISALLOWED_USER_AGENTS = []
DISCOURSE_API_KEY = '********************'
DISCOURSE_DEV_POST_SUFFIX = ''
DISCOURSE_HOST = None
DISCOURSE_PARENT_CATEGORY = 'Fragalysis targets'
DISCOURSE_USER = 'fragalysis'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_HOST_PASSWORD = '********************'
EMAIL_HOST_USER = None
EMAIL_PORT = 25
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = '********************'
EMAIL_SUBJECT_PREFIX = '[Django] '
EMAIL_TIMEOUT = None
EMAIL_USE_LOCALTIME = False
EMAIL_USE_SSL = False
EMAIL_USE_TLS = False
FILE_UPLOAD_DIRECTORY_PERMISSIONS = None
FILE_UPLOAD_HANDLERS = ['django.core.files.uploadhandler.MemoryFileUploadHandler', 'django.core.files.uploadhandler.TemporaryFileUploadHandler']
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440
FILE_UPLOAD_PERMISSIONS = 420
FILE_UPLOAD_TEMP_DIR = None
FIRST_DAY_OF_WEEK = 0
FIXTURE_DIRS = []
FORCE_SCRIPT_NAME = None
FORMAT_MODULE_PATH = None
FORM_RENDERER = 'django.forms.renderers.DjangoTemplates'
GRAPHENE = {'SCHEMA': 'fragalysis.schema.schema'}
GRAPH_MODELS = {'all_applications': True, 'group_models': True}
IGNORABLE_404_URLS = []
INSTALLED_APPS = ['django.contrib.auth', 'django.contrib.admin', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'scoring', 'network', 'viewer', 'api', 'hypothesis', 'hotspots', 'media_serve', 'xchem_db', 'bootstrap3', 'guardian', 'graphene_django', 'django_filters', 'mozilla_django_oidc', 'django_extensions', 'rest_framework', 'rest_framework.authtoken', 'rest_framework_swagger', 'webpack_loader', 'django_cleanup', 'simple_history']
INTERNAL_IPS = []
LANGUAGES = [('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')]
LANGUAGES_BIDI = ['he', 'ar', 'ar-dz', 'fa', 'ur']
LANGUAGE_CODE = 'en-us'
LANGUAGE_COOKIE_AGE = None
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_HTTPONLY = False
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_PATH = '/'
LANGUAGE_COOKIE_SAMESITE = None
LANGUAGE_COOKIE_SECURE = False
LOCALE_PATHS = []
LOGGING = {'version': 1, 'disable_existing_loggers': False, 'formatters': {'simple': {'format': '%(asctime)s %(name)s.%(funcName)s():%(lineno)s %(levelname)s # %(message)s', 'datefmt': '%Y-%m-%dT%H:%M:%S%z'}}, 'handlers': {'console': {'level': 'DEBUG', 'class': 'logging.StreamHandler', 'formatter': 'simple'}, 'rotating': {'level': 'DEBUG', 'class': 'logging.handlers.RotatingFileHandler', 'maxBytes': 5000000, 'backupCount': 10, 'filename': '/code/logs/backend.log', 'formatter': 'simple'}}, 'loggers': {'api.security': '********************', 'asyncio': {'level': 'WARNING'}, 'celery': {'level': 'INFO'}, 'django': {'level': 'INFO'}, 'mozilla_django_oidc': {'level': 'INFO'}, 'urllib3': {'level': 'INFO'}, 'paramiko': {'level': 'WARNING'}}, 'root': {'level': 'DEBUG', 'handlers': ['console', 'rotating']}}
LOGGING_CONFIG = 'logging.config.dictConfig'
LOGGING_FRAMEWORK_ROOT_LEVEL = 'DEBUG'
LOGIN_REDIRECT_URL = '/viewer/react/landing'
LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/viewer/react/landing'
LOGOUT_URL = '/accounts/logout/'
MANAGERS = []
MEDIA_ROOT = '/code/media/'
MEDIA_URL = '/media/'
MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'
MIDDLEWARE = ['django.middleware.security.SecurityMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware', 'mozilla_django_oidc.middleware.SessionRefresh']
MIGRATION_MODULES = {}
MONTH_DAY_FORMAT = 'F j'
NEOMODEL_NEO4J_BOLT_URL = 'bolt://neo4j:test@neo4j:7687'
NUMBER_GROUPING = 0
OIDC_KEYCLOAK_REALM = '********************'
OIDC_OP_AUTHORIZATION_ENDPOINT = 'https://keycloak.xchem-dev.diamond.ac.uk/auth/realms/xchem/protocol/openid-connect/auth'
OIDC_OP_JWKS_ENDPOINT = 'https://keycloak.xchem-dev.diamond.ac.uk/auth/realms/xchem/protocol/openid-connect/certs'
OIDC_OP_LOGOUT_ENDPOINT = 'https://keycloak.xchem-dev.diamond.ac.uk/auth/realms/xchem/protocol/openid-connect/logout'
OIDC_OP_LOGOUT_URL_METHOD = None
OIDC_OP_TOKEN_ENDPOINT = '********************'
OIDC_OP_USER_ENDPOINT = 'https://keycloak.xchem-dev.diamond.ac.uk/auth/realms/xchem/protocol/openid-connect/userinfo'
OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS = '********************'
OIDC_RP_CLIENT_ID = 'fragalysis-local'
OIDC_RP_CLIENT_SECRET = '********************'
OIDC_RP_SIGN_ALGO = 'RS256'
OIDC_STORE_ACCESS_TOKEN = '********************'
OIDC_STORE_ID_TOKEN = '********************'
PASSWORD_HASHERS = '********************'
PASSWORD_RESET_TIMEOUT = '********************'
PASSWORD_RESET_TIMEOUT_DAYS = '********************'
PREPEND_WWW = False
PROJECT_ROOT = '/code'
PROPOSAL_REQUIRED = True
PROPOSAL_SUPPORTED = True
REST_FRAMEWORK = {'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',), 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination', 'PAGE_SIZE': 5000, 'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.QueryParameterVersioning', 'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.SessionAuthentication', 'mozilla_django_oidc.contrib.drf.OIDCAuthentication', 'rest_framework.authentication.BasicAuthentication']}
ROOT_URLCONF = 'fragalysis.urls'
SECRET_KEY = '********************'
SECURE_BROWSER_XSS_FILTER = False
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_HSTS_SECONDS = 0
SECURE_PROXY_SSL_HEADER = "('HTTP_X_FORWARDED_PROTO', 'https')"
SECURE_REDIRECT_EXEMPT = []
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_SSL_HOST = None
SECURE_SSL_REDIRECT = False
SENTRY_DNS = 'https://27fa0675f555431aa02ca552e93d8cfb@o194333.ingest.sentry.io/1298290'
SERVER_EMAIL = 'root@localhost'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 1209600
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_FILE_PATH = None
SESSION_SAVE_EVERY_REQUEST = False
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_MODULE = 'fragalysis.settings'
SHORT_DATETIME_FORMAT = 'm/d/Y P'
SHORT_DATE_FORMAT = 'm/d/Y'
SIGNING_BACKEND = 'django.core.signing.TimestampSigner'
SILENCED_SYSTEM_CHECKS = []
SQUONK2_INSTANCE_API = '********************'
SQUONK2_MEDIA_DIRECTORY = 'fragalysis-files'
STATICFILES_DIRS = ['/code/fragalysis/../viewer/static']
STATICFILES_FINDERS = "('django.contrib.staticfiles.finders.FileSystemFinder', 'django.contrib.staticfiles.finders.AppDirectoriesFinder')"
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
STATIC_ROOT = '/code/static'
STATIC_URL = '/static/'
TARGET_LOADER_MEDIA_DIRECTORY = 'target_loader_data'
TEMPLATES = [{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': [], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages']}}]
TEST_NON_SERIALIZED_APPS = []
TEST_RUNNER = 'django.test.runner.DiscoverRunner'
THOUSAND_SEPARATOR = ','
TIME_FORMAT = 'P'
TIME_INPUT_FORMATS = ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
TIME_ZONE = 'UTC'
TOKEN_EXPIRY_MINUTES = '********************'
USE_I18N = True
USE_L10N = True
USE_THOUSAND_SEPARATOR = False
USE_TZ = True
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = False
WEBPACK_LOADER = {'DEFAULT': {'BUNDLE_DIR_NAME': 'bundles/', 'STATS_FILE': '/code/frontend/webpack-stats.json'}}
WSGI_APPLICATION = 'fragalysis.wsgi.application'
X_FRAME_OPTIONS = 'DENY'
YEAR_MONTH_FORMAT = 'F Y'


You’re seeing this error because you have DEBUG = True in your
Django settings file. Change that to False, and Django will
display a standard page generated by the handler for this status code.
```

**Comment by alanbchristie** [comment]
This seems to be caused by a disconnect between the code and the model, with the code looking for `sub_path` property of the `JobFileTransfer` record. The existing stack's model has a `sub_path` but the Fragalysis-2 code does not - we need to investigate how the code and migrations got out of step.

**Comment by boriskovar-m2ms** [comment]
Fragalysis job overrides need to be generalized also for '''fragment-network-merge-swills23''' . It was  generalized for other jobs but forgot about this one so there is still some work to do also on frontend side.
