### ISSUE TITLE
Missing .mtz files cause problems

### ISSUE THREAD

**Issue by tdudgeon** [m2ms/fragalysis-frontend#1257]
The target being processed by Jasmin Aschenbrenner is giving problems. 
```
Traceback (most recent call last):
  File "/dls/science/groups/i04-1/conor_dev/xchem-align/env_xchem_align/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/dls/science/groups/i04-1/conor_dev/xchem-align/env_xchem_align/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/dls/science/groups/i04-1/conor_dev/xchem-align/src/xchemalign/aligner.py", line 776, in <module>
    main()
  File "/dls/science/groups/i04-1/conor_dev/xchem-align/src/xchemalign/aligner.py", line 770, in main
    a.run()
  File "/dls/science/groups/i04-1/conor_dev/xchem-align/src/xchemalign/aligner.py", line 219, in run
    new_meta = self._perform_alignments(input_meta)
  File "/dls/science/groups/i04-1/conor_dev/xchem-align/src/xchemalign/aligner.py", line 317, in _perform_alignments
    datasets, reference_datasets, new_datasets = get_datasets_from_crystals(crystals, self.base_dir)
  File "/dls/science/groups/i04-1/conor_dev/xchem-align/src/xchemalign/aligner.py", line 118, in get_datasets_from_crystals
    output_path
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'
```

The corresponding code looks like this:

```
    for dtag, crystal in crystals.items():
        dataset = dt.Dataset(
            dtag=dtag,
            pdb=str(output_path / crystal[Constants.META_XTAL_FILES][Constants.META_XTAL_PDB][Constants.META_FILE]),
            xmap="",
            mtz=str(
                output_path
                / crystal[Constants.META_XTAL_FILES].get(Constants.META_XTAL_MTZ, {}).get(Constants.META_FILE)
            ),
```
Clearly a .mtz file is expected to be present, but in this case the 4 reference structures do not have .mtz files.

So either:
the .mtz files should be required and this error is correct (but could be handled better)

or: 
the code need to be tolerant of missing .mtz files.

**Comment by ConorFWild** [comment]
There should always be an mtz file? Even for reference datasets we should have one because having a pdb file without an mtz that provides the evidence for it is not great?

This needs a clearer error though.

@phraenquex Happy with that assessment?

**Comment by phraenquex** [comment]
Sorry @ConorFWild @tdudgeon, only just saw.  

In general no, there need be no mtz file - it's just a bunch of coordinates to reference against.  Someone could choose a structure from the PDB, if they wanted to.

Any reason not to make it behave just like any other compound that's missing an mtz file?

**Comment by tdudgeon** [comment]
The problem is fixed, but the solution needs tidying up so that the string "None" is not passed through to LNA.

**Comment by phraenquex** [comment]
@ConorFWild this is for you - @tdudgeon says it's a 5min change.

**Comment by phraenquex** [comment]
@tdudgeon please try to fix once @Waztom has given you rights to the repo.  

(If not easy, relabel as Yellow.)

**Comment by tdudgeon** [comment]
I took a look and it's not obvious to me what needs to change in LNA so I must leave that to @ConorFWild

**Comment by ConorFWild** [comment]
Issue addressed in commit [c6e26d3](https://github.com/xchem/xchem-align/commit/c6e26d3c5725cef9dca9f9f80d0221b3b2b99233)
