### ISSUE TITLE
Discourse 500 error and no tag created when creating a new tag

### ISSUE THREAD

**Issue by Waztom** [m2ms/fragalysis-frontend#1279]
On the staging stack, am logged in and creating a new tag yields a 500 Discourse error with no tag created. 

It is possible to delete tags.

**Comment by boriskovar-m2ms** [comment]
My guess is that stack db and discourse db are out of sync (very very easy to achieve). Getting both dbs in sync or disabling discourse would fix the problem. This is just my guess from top of my head (happened many many times before especially on dev stacks) but will check.

**Comment by boriskovar-m2ms** [comment]
@Waztom interestingly enough I was able to create and then delete tag for both uploaded targets...

**Comment by boriskovar-m2ms** [comment]
@Waztom ok I take it back. When I'm debugging staging it works because it uses dev discourse but when I just visit staging it doesn't work because it uses different discourse so I think I was right in my comment from yesterday that it's issue of staging and discourse DBs being out of sync

**Comment by boriskovar-m2ms** [comment]
Response from backend to ```/api/discourse_post``` is just generic http code 500
```html
<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
```

**Comment by Waztom** [comment]
@alanbchristie will look at disabling Discourse for Purple release (if fix is not obvious and quick).

**Comment by alanbchristie** [comment]
Discourse seems to be configured and should be available on staging stack. I am able to use the internal mechanism but am unable to reproduce the 500 error so there may be some API value that I'm missing. Can someone reproduce the error on the stack so I can inspect the backend logs?

**Comment by Waztom** [comment]
@alanbchristie I tried to create a new tag on the staging stack at 17:08 and still get the 500 error.

**Comment by alanbchristie** [comment]
The following exception was caught on the staging stack...

```
2024-01-22T15:58:05+0000 viewer.discourse.create_post():106 INFO # + discourse.create_post
2024-01-22T15:58:05+0000 viewer.discourse.get_user():18 INFO # + discourse.get_user
2024-01-22T15:58:05+0000 viewer.discourse.get_user():42 INFO # - discourse.get_user
2024-01-22T15:58:05+0000 django.request.log_response():224 ERROR # Internal Server Error: /api/discourse_post/
Traceback (most recent call last):
  File "/code/viewer/discourse.py", line 152, in process_post
    topic = DiscourseTopic.objects.get(topic_title=post_details['title'])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
viewer.models.DiscourseTopic.DoesNotExist: DiscourseTopic matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/viewer/views.py", line 1229, in create
    error, post_url, error_message = create_discourse_post(
                                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/code/viewer/discourse.py", line 217, in create_discourse_post
    error, error_message, _, post_url = process_post(
                                        ^^^^^^^^^^^^^
  File "/code/viewer/discourse.py", line 164, in process_post
    error, error_message, topic_id, post_url = create_post(
                                               ^^^^^^^^^^^^
  File "/code/viewer/discourse.py", line 132, in create_post
    post = client.create_post(content, category_id, topic_id, title, tags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydiscourse/client.py", line 768, in create_post
    return self._post(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydiscourse/client.py", line 1565, in _post
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydiscourse/client.py", line 1688, in _request
    raise DiscourseClientError(msg, response=response)
pydiscourse.exceptions.DiscourseClientError: Title has already been used
```

**Comment by Waztom** [comment]
@kaliif if LHS tags are deleted, it is not possible to recreate them due to an error when creating a Discourse post => see Alan's traceback above.

Could you please modify the Title used to create a Discourse post (see create_post in /code/viewer/discourse.py) uses the Tag name and the date/time it was created eg. Tagtitle:2011-11-04T00:05:23.

**Comment by kaliif** [comment]
@Waztom there may be multiple tags, should I include them all?

Creation timestamp, do yo mean the time the post is being created, i.e. now?

**Comment by alanbchristie** [comment]
A modified `discourse` module is in progress. It _should_ have better error handling and should handle duplicate posts more gracefully.

**Comment by Waztom** [comment]
@kaliif this only applies to when new Tags are created - need a way to avoid creating duplicate Discourse Titles.

When a Tag is created, only the Tag name/title is used for creating a Discourse post =>

![image](https://github.com/m2ms/fragalysis-frontend/assets/24798762/74978f26-2532-4d0f-94e7-eaa0a05662a0)
 
@boriskovar-m2ms, is there a simple way to ping the backend the Tag name + date/time for when Tags are created in the frontend? Means that the backend does not have to deal with different cases and can just use what the frontend sends. 

And for the time, it is the time the Tag is created in the frontend.

**Comment by boriskovar-m2ms** [comment]
@Waztom 
There is several problems with this approach. 
1. There is nothing in the API to send date time of object creation but yes I can just concatenate name of the object + date time
2. Bigger problem is that there are places in the frontend where we are constructing discourse URLs to posts for users to navigate to which currently are something like ```discourse_base_url``` + ```object_name``` but now with need to add also date/time which is information frontend doesn't (currently) have. From what I found we are doing this for targets, tags, projects (also I think every snapshot is a post in the associated project topic IIRC). Projects have ```additional_info``` field where we can add this. Tags have discourse_url so it should work.

To be honest I don't see any quick win. I think your suggestion is something that can finally fix the discourse integration but we are talking about several days of development/testing on frontend because I'm sure I missed something why I was investigating this (integration was done 3 years ago and it was big feature and this is major change - even if it doesn't look like).

Side note: also backend is creating some tags automatically but ```discourse_url``` attribute is null but there is a mechanism that when you click on the 'Discourse link' in the frontend in the 'Tag details' and discourse link doesn't exists it will create new post.

**Comment by alanbchristie** [comment]
Why ins't the date/time the time of the API call? The user in the f/e presses a button, which results in an API call. So the date/time _could be_ the date/time the backend chooses to create any corresponding DB record or the time it makes a Discourse API call?

While we're here ... what precision is the data/time recorded as? Is seconds (`2024-01-18T12:00:05`) enough to avoid two users entering the same tag at the same time?

**Comment by boriskovar-m2ms** [comment]
I don't think it really matters - it trivial in whatever manner we decided to tackle this problem, the hard part of the change is for the frontend to reconstruct the name of the post.

**Comment by kaliif** [comment]
Just so we're clear, should I continue with what Warren suggested and add the tag to title or we're still thinking?

**Comment by Waztom** [comment]
@alanbchristie and @kaliif is it possible to see if the Discourse topic exists and if so skip creating a post? You have worked through the logic of handling the create_post function.  

To be very clear, Discourse is a very far second place to tagging and getting data uploaded to Fragalysis. The solution needs to allow tags to be created and recreated (if they have been deleted in the past).

**Comment by phraenquex** [comment]
Summary:  Discourse actually makes the real fix rather hard.  So that makes this a yellow-release ticket.

**Comment by mwinokan** [comment]
Discourse is not currently in use

**Comment by alanbchristie** [comment]
And I believe the issue is avoided by recent changes. Suggest we drop this issue and raise a new one when we see a fault.
