### ISSUE TITLE
xtalforms -> crystalforms in assemblies.yaml

### ISSUE THREAD

**Issue by phraenquex** [m2ms/fragalysis-frontend#1324]
in assemblies.yaml, the keyword should be `crystalforms` (currently `xtalforms`).

**Comment by tdudgeon** [comment]
@ConorFWild I have changes for this (small change to XCA and LNA). Just checking that you're not working on this too.

**Comment by tdudgeon** [comment]
@ConorFWild I committed my changes to XCA and LNA repos, both on `issue_1324` branch. Could you take a look.
There's a lot more involved that just the code changes as the tests, docs and examples needed to be updated.
You will need to take a look at updating `xtalforms_example.md` and the diagram that is in `USER-GUIDE.md`.
Also, what might have I missed in the examples and docs?

Once these changes are live @kaliif will need to update the target loader.
And we'll need to retest everything.

**Comment by phraenquex** [comment]
To do: 
* update examples
* update tests
* update docs (Readme)

**Comment by Waztom** [comment]
@ConorFWild to update/confirm changes are correct and working, ready to be merged to Master branch for deployment to software folder.

**Comment by ConorFWild** [comment]
Tested and should be safe to merge!

**Comment by ConorFWild** [comment]
(merged)

**Comment by tdudgeon** [comment]
I've tested the merged changes and all looks good with my copies of the lb32627-65 and lb32627-66 data.
I will update the users environment.

**Comment by phraenquex** [comment]
@ConorFWild we don't close tickets - that removes them from the swimlanes, Very Bad Juju.  

We either move them to the next swimlane, or we alert the next person that you're done.  

In this case, you're meant to alert @kaliif (because of [this comment](https://github.com/m2ms/fragalysis-frontend/issues/1324#issuecomment-1929404064)).  

(Tickets only ever end up in one of these swimlanes:  "In production" or "Invalid".  And only after discussion, testing and agreement.)

**Comment by phraenquex** [comment]
@ConorFWild please never close tickets - just hand them on to the next person (@kaliif in this case) or move them to the next swimlane.  

(No, it's not weird - it's our convention.)

**Comment by tdudgeon** [comment]
Moving to Dev done as #1325 is handling the documentation

**Comment by phraenquex** [comment]
(/dls/science/groups/i04-1/software/xchem-align/env_xchem_align) cs03r-sc-serv-36:/dls/labxchem/data/lb32633/lb32633-6/processing/analysis/xchemalign 1004$ python /dls/science/groups/i04-1/software/xchem-align/scripts/collate.py -c config.yaml
using GIT repo of /dls/science/groups/i04-1/software/xchem-align

Traceback (most recent call last):
  File "/dls/science/groups/i04-1/software/xchem-align/scripts/collate.py", line 5, in <module>
    from xchemalign.collator import Collator
  File "/dls/science/groups/i04-1/software/xchem-align/src/xchemalign/collator.py", line 32, in <module>
    from xchemalign import repo_info
  File "/dls/science/groups/i04-1/software/xchem-align/src/xchemalign/repo_info.py", line 30, in <module>
    data = generate(repo_dir)
  File "/dls/science/groups/i04-1/software/xchem-align/src/xchemalign/repo_info.py", line 15, in generate
    data[Constants.META_GIT_INFO_SHA] = repo.head.commit.hexsha
  File "/dls/science/groups/i04-1/software/xchem-align/env_xchem_align/lib/python3.10/site-packages/git/refs/symbolic.py", line 293, in _get_commit
    obj = self._get_object()
  File "/dls/science/groups/i04-1/software/xchem-align/env_xchem_align/lib/python3.10/site-packages/git/refs/symbolic.py", line 284, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/dls/science/groups/i04-1/software/xchem-align/env_xchem_align/lib/python3.10/site-packages/git/objects/base.py", line 98, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "/dls/science/groups/i04-1/software/xchem-align/env_xchem_align/lib/python3.10/site-packages/git/db.py", line 44, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
  File "/dls/science/groups/i04-1/software/xchem-align/env_xchem_align/lib/python3.10/site-packages/git/cmd.py", line 1461, in get_object_header
    return self.__get_object_header(cmd, ref)
  File "/dls/science/groups/i04-1/software/xchem-align/env_xchem_align/lib/python3.10/site-packages/git/cmd.py", line 1447, in __get_object_header
    return self._parse_object_header(cmd.stdout.readline())
  File "/dls/science/groups/i04-1/software/xchem-align/env_xchem_align/lib/python3.10/site-packages/git/cmd.py", line 1406, in _parse_object_header
    raise ValueError(err_msg)
ValueError: SHA is empty, possible dubious ownership in the repository at /dls/science/groups/i04-1/software/xchem-align.
            If this is unintended run:

                      "git config --global --add safe.directory /dls/science/groups/i04-1/software/xchem-align"

**Comment by tdudgeon** [comment]
User has not run the "run once" configuration described in the user guide:
https://github.com/xchem/xchem-align/blob/master/USER-GUIDE.md#1-enabling-the-xchemalign-environment

**Comment by Waztom** [comment]
@kaliif can you please check and confirm if xtalform is still being called somewhere in the loader?

Tried uploading and got the following error, please see assemblies.txt that was used.  

![image](https://github.com/m2ms/fragalysis-frontend/assets/24798762/db458762-1489-46f4-ae39-8436f4de6ca
[config.txt](https://github.com/m2ms/fragalysis-frontend/files/14196634/config.txt)
[assemblies.txt](https://github.com/m2ms/fragalysis-frontend/files/14196633/assemblies.txt)
5)

**Comment by tdudgeon** [comment]
I believe this change in target loader (trivial change) is still pending as we need data to test from upstream issues.
You should be able to test "manually" by un tar gzipping the upload, rename the tag in `assemblies.yaml` and re tar gzipping.

As for the error I think the "ERROR: 'xtalforms' section missing ..." is OK, as this will not happen once the codes are in sync, and we have proper versioning in place.

**Comment by Waztom** [comment]
@tdudgeon this change will require fronted work - is there any reason not to push the trivial change to staging for @boriskovar-m2ms to dev/test.
