### ISSUE TITLE
Handle missing chains in PDB files

### ISSUE THREAD

**Issue by tdudgeon** [m2ms/fragalysis-frontend#1337]
The PDB files that are the inputs to XCA sometimes have unexpected chain names. For instance, the `assemlies.yaml` expects chains A and B, but the PDB files that are generated use chain M and N, and the chain names can change over time (e.g. initially being A and B but changing at some point to M and N).

Currently when this happens the LNA code doing the alignments blows up with a traceback like this:
```
Traceback (most recent call last):
  File "/dls/science/groups/i04-1/software/xchem-align/scripts/align.py", line 56, in <module>
    main()
  File "/dls/science/groups/i04-1/software/xchem-align/scripts/align.py", line 43, in main
    a.run()
  File "/dls/science/groups/i04-1/software/xchem-align/src/xchemalign/aligner.py", line 232, in run
    new_meta = self._perform_alignments(input_meta)
  File "/dls/science/groups/i04-1/software/xchem-align/src/xchemalign/aligner.py", line 437, in _perform_alignments
    updated_fs_model = _update(
  File "/dls/science/groups/i04-1/software/xchem-align/env_xchem_align/lib/python3.10/site-packages/ligand_neighbourhood_alignment/cli.py", line 1105, in _update
    neighborhoods = _get_neighbourhoods(dataset, xtalform, assemblies, version)
  File "/dls/science/groups/i04-1/software/xchem-align/env_xchem_align/lib/python3.10/site-packages/ligand_neighbourhood_alignment/cli.py", line 627, in _get_neighbourhoods
    dataset_ligand_neighbourhoods: dict[tuple[str, str, str, str], dt.Neighbourhood] = _get_dataset_neighbourhoods(
  File "/dls/science/groups/i04-1/software/xchem-align/env_xchem_align/lib/python3.10/site-packages/ligand_neighbourhood_alignment/cli.py", line 589, in _get_dataset_neighbourhoods
    assembly = _generate_assembly(xtalform, structure, assemblies)
  File "/dls/science/groups/i04-1/software/xchem-align/env_xchem_align/lib/python3.10/site-packages/ligand_neighbourhood_alignment/cli.py", line 524, in _generate_assembly
    chain_clone = structure[0][_chain].clone()
ValueError: Chain B not found (only [A W])
```

There are 2 probable solutions to this.

1. adapt the LNA code (cli.py around line 523) to check for the presence of the expected chain, and throw an informative error telling the user which crystal is involved.
2. Handle this as an additional validation step in collator, but this means that collator will have to inspect the PDB files to check their validity (currently collator only copies the files, doesn't look into them)

**Comment by Waztom** [comment]
@tdudgeon and @ConorFWild suggest for Purple release, we should report chain inconsistencies back to the user. For the Yellow release, @ConorFWild suggests chain mapping option in the assemblies.yaml config. @tdudgeon and @ConorFWild will review how and if this can be implemented in the validator step.

**Comment by phraenquex** [comment]
@ConorFWild still needs to specify which dataset is giving a problem.
