### ISSUE TITLE
DB connection failure

### ISSUE THREAD

**Issue by alanbchristie** [m2ms/fragalysis-frontend#1415]
Seen by Max and an indication that there may be connection issues between the stack and its database: -

```
Traceback (most recent call last): File "/.venv/lib/python3.11/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection self.connect() File "/.venv/lib/python3.11/site-packages/sentry_sdk/integrations/django/__init__.py", line 677, in connect return real_connect(self) ^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/utils/asyncio.py", line 33, in inner return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/backends/base/base.py", line 200, in connect self.connection = self.get_new_connection(conn_params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/utils/asyncio.py", line 33, in inner return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection connection = Database.connect(**conn_params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect conn = _connect(dsn, connection_factory=connection_factory, **kwasync) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ psycopg2.OperationalError: could not translate host name "database.v2-production-stack.svc" to address: Temporary failure in name resolution The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/.venv/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task R = retval = fun(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 306, in _inner reraise(*exc_info) File "/.venv/lib/python3.11/site-packages/sentry_sdk/_compat.py", line 115, in reraise raise value File "/.venv/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 301, in _inner return f(*args, **kwargs) ^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__ return self.run(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/code/viewer/tasks.py", line 310, in validate_compound_set validate_dict = check_refmol(m, validate_dict, target) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/code/viewer/sdf_check.py", line 96, in check_refmol if len(query) == 0: ^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 262, in __len__ self._fetch_all() File "/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1324, in _fetch_all self._result_cache = list(self._iterable_class(self)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 51, in __iter__ results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql cursor = self.connection.cursor() ^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/utils/asyncio.py", line 33, in inner return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/backends/base/base.py", line 259, in cursor return self._cursor() ^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/backends/base/base.py", line 235, in _cursor self.ensure_connection() File "/.venv/lib/python3.11/site-packages/django/utils/asyncio.py", line 33, in inner return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/backends/base/base.py", line 218, in ensure_connection with self.wrap_database_errors: File "/.venv/lib/python3.11/site-packages/django/db/utils.py", line 90, in __exit__ raise dj_exc_value.with_traceback(traceback) from exc_value File "/.venv/lib/python3.11/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection self.connect() File "/.venv/lib/python3.11/site-packages/sentry_sdk/integrations/django/__init__.py", line 677, in connect return real_connect(self) ^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/utils/asyncio.py", line 33, in inner return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/backends/base/base.py", line 200, in connect self.connection = self.get_new_connection(conn_params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/utils/asyncio.py", line 33, in inner return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection connection = Database.connect(**conn_params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect conn = _connect(dsn, connection_factory=connection_factory, **kwasync) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ django.db.utils.OperationalError: could not translate host name "database.v2-production-stack.svc" to address: Temporary failure in name resolution
```

**Comment by mwinokan** [comment]
@alanbchristie was unable to reproduce but he says that this error could appear anywhere in the deployment, so unsure how to catch this and give a more sensible error.
