### ISSUE TITLE
[RHS] Using up/down buttons causes errors in console

### ISSUE THREAD

**Issue by simonadachova** [m2ms/fragalysis-frontend#1424]
- few compounds are selected in RHS
- click on up/down buttons 
- error in console :

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'nextSibling')
    at _callee2$ (main-e8e6d88….js:2:3108584)
    at tryCatch (main-e8e6d88….js:2:3082926)
    at Generator.<anonymous> (main-e8e6d88….js:2:3084727)
    at Generator.next (main-e8e6d88….js:2:3083438)
    at asyncGeneratorStep (main-e8e6d88….js:2:3090400)
    at _next (main-e8e6d88….js:2:3090654)
    at main-e8e6d88….js:2:3090779
    at new Promise (<anonymous>)
    at main-e8e6d88….js:2:3090583
    at handleClickOnDownArrow (main-e8e6d88….js:2:3109078)

https://github.com/m2ms/fragalysis-frontend/assets/104004432/61e96ff8-2a90-4b54-9644-6bb913cd66ff

**Comment by mwinokan** [comment]
Await #1748
