### ISSUE TITLE
RHS upload incompatible with API changes (target has no attribute `project_set`)

### ISSUE THREAD

**Issue by mwinokan** [m2ms/fragalysis-frontend#1493]
When uploading [A71EV2A_Knitwork_June_fragalysis.sdf.zip](https://github.com/user-attachments/files/16834884/A71EV2A_Knitwork_June_fragalysis.sdf.zip) to A71EV2A on staging I received the following error:

```
Traceback (most recent call last): File "/code/viewer/cset_upload.py", line 281, in create_mol ).distinct().get( ^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 435, in get raise self.model.DoesNotExist( viewer.models.Compound.DoesNotExist: Compound matching query does not exist. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/.venv/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task R = retval = fun(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 325, in _inner reraise(*exc_info) File "/.venv/lib/python3.11/site-packages/sentry_sdk/_compat.py", line 127, in reraise raise value File "/.venv/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 320, in _inner return f(*args, **kwargs) ^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__ return self.run(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/code/viewer/tasks.py", line 106, in process_compound_set compound_set = save_mols.task() ^^^^^^^^^^^^^^^^ File "/code/viewer/cset_upload.py", line 685, in task _ = self.process_mol( ^^^^^^^^^^^^^^^^^ File "/code/viewer/cset_upload.py", line 559, in process_mol cpd = self.set_mol(mol, target, compound_set, filename, zfile, zfile_hashvals) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/code/viewer/cset_upload.py", line 369, in set_mol compound: Compound = self.create_mol( ^^^^^^^^^^^^^^^^ File "/code/viewer/cset_upload.py", line 303, in create_mol for project in target.project_set.all(): ^^^^^^^^^^^^^^^^^^ AttributeError: 'Target' object has no attribute 'project_set'

/viewer/upload_task/28206884-ae76-49a9-a7b9-7046b42b6e63/
```

@kaliif any idea what this error is?

**Comment by alanbchristie** [comment]
This seems to be an issue caused by the failure of the automatic merge. Code fixed some time ago seems to have returned. We have just fixed the issue again and a new release to staging is on the way.

**Comment by mwinokan** [comment]
RHS upload confirmed to be working again
