### ISSUE TITLE
RHS (name,method) unique constraint persists even if CompoundSets are deleted

### ISSUE THREAD

**Issue by mwinokan** [m2ms/fragalysis-frontend#1602]
To reproduce:

1. Upload a RHS compoundset (e.g. [Recipe_1LPUPHX_poses.sdf.zip](https://github.com/user-attachments/files/18035250/Recipe_1LPUPHX_poses.sdf.zip) for target `A71EV2A`) with `(name, method) = ("Max Winokan", "HIPPO_Recipe_1LPUPHX")`
2. Delete that compound set using the `upload_cset` endpoint
3. Re-upload the same file.

Error:

```
Traceback (most recent call last): File "/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 581, in get_or_create return self.get(**kwargs), False ^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 435, in get raise self.model.DoesNotExist( viewer.models.ComputedSetSubmitter.DoesNotExist: ComputedSetSubmitter matching query does not exist. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute return super().execute(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "viewer_computedsetsubmitter_name_method_09cdfd9c_uniq" DETAIL: Key (name, method)=(Max Winokan, HIPPO_Recipe_1LPUPHX) already exists. The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/code/viewer/cset_upload.py", line 764, in task mols_to_process, score_descriptions = self.set_descriptions( ^^^^^^^^^^^^^^^^^^^^^^ File "/code/viewer/cset_upload.py", line 640, in set_descriptions computed_set.submitter = self.get_submission_info(description_mol) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/code/viewer/cset_upload.py", line 578, in get_submission_info return ComputedSetSubmitter.objects.get_or_create( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method return getattr(self.get_queryset(), name)(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 588, in get_or_create return self.create(**params), True ^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 453, in create obj.save(force_insert=True, using=self.db) File "/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 739, in save self.save_base(using=using, force_insert=force_insert, File "/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 776, in save_base updated = self._save_table( ^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 881, in _save_table results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 919, in _do_insert return manager._insert( ^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method return getattr(self.get_queryset(), name)(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1270, in _insert return query.get_compiler(using=using).execute_sql(returning_fields) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql cursor.execute(sql, params) File "/.venv/lib/python3.11/site-packages/sentry_sdk/integrations/django/__init__.py", line 644, in execute result = real_execute(self, sql, params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 66, in execute return self._execute_with_wrappers(sql, params, many=False, executor=self._execute) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers return executor(sql, params, many, context) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in _execute with self.db.wrap_database_errors: File "/.venv/lib/python3.11/site-packages/django/db/utils.py", line 90, in __exit__ raise dj_exc_value.with_traceback(traceback) from exc_value File "/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute return super().execute(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ django.db.utils.IntegrityError: duplicate key value violates unique constraint "viewer_computedsetsubmitter_name_method_09cdfd9c_uniq" DETAIL: Key (name, method)=(Max Winokan, HIPPO_Recipe_1LPUPHX) already exists. The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/.venv/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task R = retval = fun(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 325, in _inner reraise(*exc_info) File "/.venv/lib/python3.11/site-packages/sentry_sdk/_compat.py", line 127, in reraise raise value File "/.venv/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 320, in _inner return f(*args, **kwargs) ^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__ return self.run(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/code/viewer/tasks.py", line 105, in process_compound_set compound_set, process_messages = save_mols.task() ^^^^^^^^^^^^^^^^ File "/code/viewer/cset_upload.py", line 794, in task raise ValueError(exc.args[0]) from exc ValueError: duplicate key value violates unique constraint "viewer_computedsetsubmitter_name_method_09cdfd9c_uniq" DETAIL: Key (name, method)=(Max Winokan, HIPPO_Recipe_1LPUPHX) already exists.

/viewer/upload_task/d121297e-d41d-4542-8b88-5b533cd7186e/
```

**Comment by mwinokan** [comment]
@kaliif maybe this has something to do with only one of ComputedSet and ComputedSetSubmitter being deleted?

**Comment by kaliif** [comment]
@mwinokan I'm afraid for now, I have to go with "it works on my machine" as I haven't been able to reproduce this. The recipe you gave above, correctly creates, deletes, and recreates the set for me both locally and in my stack. Do you have any more details to add?
Looking at the code doesn't shed any light on the matter either. The unique constraint you mention does prevent creating duplicate submitter objects, but during the upload, it's being fetched with django's `get_or_create` method, so if the submitter already exists, it won't stop the upload.

**Comment by mwinokan** [comment]
@mwinokan to iron out more reproducible bug report

**Comment by mwinokan** [comment]
@kaliif could we please revisit this ticket. There have been some instances recently where I am hitting unique constraints on RHS uploads which I don't think are specced.

Currently on staging if I try to upload [D68EV3C_iter1_fstein_fragalysis.sdf.zip](https://github.com/user-attachments/files/19449845/D68EV3C_iter1_fstein_fragalysis.sdf.zip) to `D68EV3C` (`lb18145-1`) I get this traceback:

```

Traceback (most recent call last): File "/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 581, in get_or_create return self.get(**kwargs), False ^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 435, in get raise self.model.DoesNotExist( viewer.models.ComputedSetSubmitter.DoesNotExist: ComputedSetSubmitter matching query does not exist. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute return super().execute(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "viewer_computedsetsubmitter_name_method_09cdfd9c_uniq" DETAIL: Key (name, method)=(Max Winokan, iter1_fstein) already exists. The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/code/viewer/cset_upload.py", line 837, in task mols_to_process, score_descriptions = self.set_descriptions( ^^^^^^^^^^^^^^^^^^^^^^ File "/code/viewer/cset_upload.py", line 698, in set_descriptions computed_set.submitter = self.get_submission_info(description_mol) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/code/viewer/cset_upload.py", line 614, in get_submission_info return ComputedSetSubmitter.objects.get_or_create( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method return getattr(self.get_queryset(), name)(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 588, in get_or_create return self.create(**params), True ^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 453, in create obj.save(force_insert=True, using=self.db) File "/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 739, in save self.save_base(using=using, force_insert=force_insert, File "/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 776, in save_base updated = self._save_table( ^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 881, in _save_table results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/base.py", line 919, in _do_insert return manager._insert( ^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 85, in manager_method return getattr(self.get_queryset(), name)(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1270, in _insert return query.get_compiler(using=using).execute_sql(returning_fields) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql cursor.execute(sql, params) File "/.venv/lib/python3.11/site-packages/sentry_sdk/integrations/django/__init__.py", line 644, in execute result = real_execute(self, sql, params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 66, in execute return self._execute_with_wrappers(sql, params, many=False, executor=self._execute) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers return executor(sql, params, many, context) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in _execute with self.db.wrap_database_errors: File "/.venv/lib/python3.11/site-packages/django/db/utils.py", line 90, in __exit__ raise dj_exc_value.with_traceback(traceback) from exc_value File "/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/django_prometheus/db/common.py", line 69, in execute return super().execute(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ django.db.utils.IntegrityError: duplicate key value violates unique constraint "viewer_computedsetsubmitter_name_method_09cdfd9c_uniq" DETAIL: Key (name, method)=(Max Winokan, iter1_fstein) already exists. The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/.venv/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task R = retval = fun(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 325, in _inner reraise(*exc_info) File "/.venv/lib/python3.11/site-packages/sentry_sdk/_compat.py", line 127, in reraise raise value File "/.venv/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 320, in _inner return f(*args, **kwargs) ^^^^^^^^^^^^^^^^^^ File "/.venv/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__ return self.run(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/code/viewer/tasks.py", line 106, in process_compound_set compound_set, process_messages = save_mols.task() ^^^^^^^^^^^^^^^^ File "/code/viewer/cset_upload.py", line 867, in task raise ValueError(exc.args[0]) from exc ValueError: duplicate key value violates unique constraint "viewer_computedsetsubmitter_name_method_09cdfd9c_uniq" DETAIL: Key (name, method)=(Max Winokan, iter1_fstein) already exists.

/viewer/upload_task/26c29b13-d959-4ca7-a6c3-7754de99faad/
```

Can you spot anything in the logs that tells you which compoundset this is clashing with?

If I recall correctly, we never specced that the `(name, method)` should be unique. Instead on a RHS upload:

- A unique compoundset name is generated from the method string and date (with an extra character)
- These compoundsets are restricted only within their `(target, proposal)`

Hopefully the staging DB is enough to debug, else I believe the following will also let you reproduce the error on a clean stack:

- upload D68EV3C_20250131.tgz to staging
- upload [D68EV3C_iter1_fstein_fragalysis.sdf.zip](https://github.com/user-attachments/files/19449845/D68EV3C_iter1_fstein_fragalysis.sdf.zip)
- delete compound set via `upload_cset`
- attempt to upload [D68EV3C_iter1_fstein_fragalysis.sdf.zip](https://github.com/user-attachments/files/19449845/D68EV3C_iter1_fstein_fragalysis.sdf.zip) again

**Comment by kaliif** [comment]
@mwinokan it's exactly the same error as above, the unique constraint does not come from the `ComputedSet` but `ComputedSetSubmitter` which requires a unique combination of `name` (submitter's name from file) and `method` fields.

Nevertheless, I spotted the error and managed to reproduce the issue. While I'm fixin this, it occurs to me that `name` and `method` combo is not the best test here and I suggest, since it's collecting user's email, to use that instead -  so change the unique constraint to use `email` + `method` instead. OK to proceed? Or should I keep it as name?

**Comment by mwinokan** [comment]
@kaliif that's fine, you can change it to email. 

Why is this unique constraint desirable on `ComputedSetSubmitter` in the first place?

**Comment by kaliif** [comment]
@mwinokan probably do reduce the clutter, this way it won't create submitter with each upload. But I don't know the original reasoning, it was before my time.

**Comment by mwinokan** [comment]
@kaliif I see, perhaps it would have been more elegant to have a separate submitter for each user. But this is fine for now (as long as uploads are not prevented by the unique constraint, as they are in this bug)
