### ISSUE TITLE
Add job definitions for fragmenstein place and fragmenstein multiplex

### ISSUE THREAD

**Issue by rsanchezgarc** [m2ms/fragalysis-frontend#970]

**Comment by boriskovar-m2ms** [comment]
@alanbchristie  Seems to be working but it seems that result file upload after a job finishes always fails.

**Comment by alanbchristie** [comment]
There is an exception in the Stack container's `/code/logs/backend.log` file...

```
2022-12-20T07:38:30 viewer.views.create():3324 INFO # + JobRequest.post
2022-12-20T07:38:30 viewer.squonk_job_request.create_squonk_job():90 INFO # + create_squonk_job
2022-12-20T07:38:30 viewer.squonk_job_request.create_squonk_job():100 INFO # + squonk_job_name=fragmenstein-combine
2022-12-20T07:38:30 viewer.squonk_job_request.create_squonk_job():101 INFO # + target_id=69
2022-12-20T07:38:30 viewer.squonk_job_request.create_squonk_job():102 INFO # + snapshot_id=1426
2022-12-20T07:38:30 viewer.squonk_job_request.create_squonk_job():103 INFO # + squonk_project=project-8f32b412-8329-4469-a39c-8581efa93796
2022-12-20T07:38:30 viewer.squonk_job_request.create_squonk_job():104 INFO # + squonk_job_spec={"collection":"fragmenstein","job":"fragmenstein-combine","version":"1.0.0","variables":{"fragments":["fragalysis-files/CD44MMA/CD44MMA-x0017_0A.mol","fragalysis-files/CD44MMA/CD44MMA-x0049_0A.mol"],"outfile":"merged.sdf","count":5,"keepHydrogens":false,"fragIdField":"_Name","smilesFieldName":"original SMILES","proteinFieldName":"ref_pdb","proteinFieldValue":"undefined","protein":"fragalysis-files/CD44MMA/CD44MMA-x0077_0A_apo-desolv.pdb"}}
2022-12-20T07:38:30 viewer.squonk_job_request.create_squonk_job():137 INFO # + job_name=boris.kovar-2022-12-20
2022-12-20T07:38:30 viewer.squonk_job_request.create_squonk_job():138 INFO # + callback_url=https://fragalysis-tibor-default.xchem-dev.diamond.ac.uk/api/job_callback/d77d9ba5-3a92-45a6-b553-66a087bec3b9/
2022-12-20T07:38:30 viewer.squonk_job_request.create_squonk_job():139 INFO # + Calling DmApi.start_job_instance(boris.kovar-2022-12-20)
2022-12-20T07:38:30 mozilla_django_oidc.middleware.process_request():113 DEBUG # request is not refreshable
2022-12-20T07:38:30 viewer.views.update():3405 INFO # + JobCallBackView.update(code=d77d9ba5-3a92-45a6-b553-66a087bec3b9) jr=JobRequest object (81)
2022-12-20T07:38:30 viewer.views.update():3422 INFO # code=d77d9ba5-3a92-45a6-b553-66a087bec3b9 status=PENDING ignoring (no status change)
2022-12-20T07:38:31 mozilla_django_oidc.middleware.process_request():113 DEBUG # request is not refreshable
2022-12-20T07:38:31 viewer.views.update():3405 INFO # + JobCallBackView.update(code=d77d9ba5-3a92-45a6-b553-66a087bec3b9) jr=JobRequest object (81)
2022-12-20T07:38:31 viewer.views.update():3436 INFO # code=d77d9ba5-3a92-45a6-b553-66a087bec3b9 status=STARTED transition_time=2022-12-20T07:38:31 (new status)
2022-12-20T07:38:31 viewer.views.update():3440 INFO # Setting job START datetime (2022-12-20T07:38:31)
2022-12-20T07:38:31 viewer.squonk_job_request.create_squonk_job():163 INFO # + SUCCESS. Job "boris.kovar-2022-12-20" started (job_instance_id=instance-2dd4a359-d255-4d26-a199-047fb2694d1f job_task_id=task-4323b923-bd47-4a61-933c-28aed3b5854e)
2022-12-20T07:38:31 viewer.views.create():3344 INFO # SUCCESS (job_id=81 squonk_url_ext=data-manager-ui/results/instance/instance-2dd4a359-d255-4d26-a199-047fb2694d1f)
2022-12-20T07:38:31 mozilla_django_oidc.middleware.process_request():120 DEBUG # id token is still valid (1671533580.3828852 > 1671521911.2539184)
2022-12-20T07:38:31 mozilla_django_oidc.middleware.process_request():120 DEBUG # id token is still valid (1671533580.3828852 > 1671521911.2550433)
2022-12-20T07:38:31 mozilla_django_oidc.middleware.process_request():120 DEBUG # id token is still valid (1671533580.3828852 > 1671521911.342168)
2022-12-20T07:38:31 mozilla_django_oidc.middleware.process_request():120 DEBUG # id token is still valid (1671533580.3828852 > 1671521911.436678)
2022-12-20T07:38:31 mozilla_django_oidc.middleware.process_request():120 DEBUG # id token is still valid (1671533580.3828852 > 1671521911.5332577)
2022-12-20T07:40:59 mozilla_django_oidc.middleware.process_request():113 DEBUG # request is not refreshable
2022-12-20T07:40:59 viewer.views.update():3405 INFO # + JobCallBackView.update(code=d77d9ba5-3a92-45a6-b553-66a087bec3b9) jr=JobRequest object (81)
2022-12-20T07:40:59 viewer.views.update():3436 INFO # code=d77d9ba5-3a92-45a6-b553-66a087bec3b9 status=SUCCESS transition_time=2022-12-20T07:40:59 (new status)
2022-12-20T07:40:59 viewer.views.update():3447 INFO # Setting job FINISH datetime (2022-12-20T07:40:59)
2022-12-20T07:40:59 viewer.views.update():3457 INFO # Job finished (SUCCESS). Can we upload the results..?
2022-12-20T07:40:59 django.request.log_response():230 ERROR # Internal Server Error: /api/job_callback/d77d9ba5-3a92-45a6-b553-66a087bec3b9/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/viewer/views.py", line 3467, in update
    jr_job_info_msg = jr.squonk_job_info[1]
TypeError: 'NoneType' object is not subscriptable
```

This is relatively old code so I'm confused that we're now seeing this sort of failure. The code is failing because it's unable to find the `command` in the **JobRequet** `squonk_job_info`. The content's either changed or something else is wrong.

Investigation of the JobRequest record content will highlight the problem. But the code could probably do with more robust handling of record content mis-configurations.

**Comment by alanbchristie** [comment]
There is a callback **race condition**!

The original **JobRequest** record is still being adjusted (between `Calling DmApi.start_job_instance` and `SUCCESS. Job "boris.kovar-2022-12-20" started`) when two callbacks come from Squonk2. These report a `PENDING` and then `STARTED` status.

## Proposed fix
Somehow we need to ensure the Fragalysis **JobRequest** record is properly/fully populated before we receive any callbacks.

**Comment by alanbchristie** [comment]
An improved Squonk (version `1.0.28`) and new Squonk Python client (version `1.15.1`) should improve matters. Squonk has been re-deployed everywhere now and, based on these changes, I have also tweaked the backend to (_hopefully_) resolve the race condition.

An experimental backend image can be found in `alanbchristie/fragalysis-backend:970-patch-1`. If this works we can merge the 970-patch branch into the main code.
