### ISSUE TITLE
Stabilise upload & download (etc) with exception handling of model get() calls

### ISSUE THREAD

**Issue by alanbchristie** [m2ms/fragalysis-frontend#990]
Original title: "Numerous model get() calls without handling "DoesNotExist" [viewer/views.py]"

Although not catastrophic it results in a rather unpleasant **500** error being received by the client (f/e or API): -

```
2022-09-18T07:01:30 django.request.log_response():230 ERROR # Internal Server Error: /viewer/compound_set/DemetriMoustakas-OEDocking/FRED/V04853/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/viewer/views.py", line 1442, in cset_download
    compound_set = ComputedSet.objects.get(unique_name=name)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 431, in get
    self.model._meta.object_name
viewer.models.ComputedSet.DoesNotExist: ComputedSet matching query does not exist.
```

Calls to `get()` for a model record should gracefully handle the `DoesNotExist` exception and instead pass back a **404** (**Not Found**) error.

There are 8 instances of this in t `viewer/views.py` but this may be an issue in other modules.

**Comment by mwinokan** [comment]
Parking until these errors appear again
